spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true

---

spring:
  config:
    activate:
      on-profile: default

---

spring:
  config:
    activate:
      on-profile: local-ky
