spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
cloud.aws:
  region:
    static: ap-northeast-2
  s3:
    bucket: sungan-app
  credentials:
    access-key: AKIAZ23FDEPWRSUYI26K
    secret-key: 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

---

spring:
  config:
    activate:
      on-profile: default

---

spring:
  config:
    activate:
      on-profile: local-ky
