spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true

---

spring:
  profiles:
    active: default

---

spring:
  profiles:
    active: local-ky
