spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: jdbc:mysql://sungan-db-0.cmsebdllgluu.ap-northeast-2.rds.amazonaws.com:3306/sungan-post-service?useSSL=false
    username: sungan
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: tr347814