spring:
  datasource:
    url: jdbc:mysql://sungan-db.cmsebdllgluu.ap-northeast-2.rds.amazonaws.com:3306/sungan-post-service?useSSL=false
    username: sungan
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: tr347814
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true